Run all tests:
    when: manual
    image: vladshambaryan/git_lab_tests
    artifacts:
        when: always
        expire_in: 10 days
        paths:
            - allure-report
    before_script:
        - pip install -r requirements.txt
    script:
        - pytest --alluredir=allure-results
    after_script:
        - allure generate -c allure-results -o allure-report 
        - echo "Report path:https://vladshambaryan.gitlab.io/-/Test_UI_Project_POM/-/jobs/${CI_JOB_ID}/artifacts/allure-report/index.html"   



Run smoke tests:
    when: manual
    image: vladshambaryan/git_lab_tests
    artifacts:
        when: always
        expire_in: 10 days
        paths:
            - allure-report
    before_script:
        - pip install -r requirements.txt
    script:
        - pytest -m smoke --alluredir=allure-results
    after_script:
        - allure generate -c allure-results -o allure-report 
        - echo "Report path:https://vladshambaryan.gitlab.io/-/Test_UI_Project_POM/-/jobs/${CI_JOB_ID}/artifacts/allure-report/index.html"  


Run regression tests:
    when: manual
    image: vladshambaryan/git_lab_tests
    artifacts:
        when: always
        expire_in: 10 days
        paths:
            - allure-report
    before_script:
        - pip install -r requirements.txt
    script:
        - pytest -m regression --alluredir=allure-results
    after_script:
        - allure generate -c allure-results -o allure-report 
        - echo "Report path:https://vladshambaryan.gitlab.io/-/Test_UI_Project_POM/-/jobs/${CI_JOB_ID}/artifacts/allure-report/index.html"  


Run extended tests:
    when: manual
    image: vladshambaryan/git_lab_tests
    artifacts:
        when: always
        expire_in: 10 days
        paths:
            - allure-report
    before_script:
        - pip install -r requirements.txt
    script:
        - pytest -m extended --alluredir=allure-results
    after_script:
        - allure generate -c allure-results -o allure-report 
        - echo "Report path:https://vladshambaryan.gitlab.io/-/Test_UI_Project_POM/-/jobs/${CI_JOB_ID}/artifacts/allure-report/index.html"   

        
              